# Changes here will be overwritten by Copier
_commit: v2.0.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: sylvie.dagoret-campagne@ijclab.in2p3.fr
author_name: Sylvie Dagoret-Campagne
custom_install: false
package_name: delightanah5
project_license: MIT
project_name: delightanah5
project_organization: LSSTDESC
